version: 2.1
orbs:
  node: circleci/node@4
jobs:
  test:
    executor:
      name: node/default
      tag: 'current'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Linter
          command: npm run lint
      - run:
          name: TSC
          command: npx tsc

workflows:
  version: 2
  test:
    jobs:
      - test
