name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install Dependencies
        id: install-deps
        run: npm ci

      - name: Lint
        id: lint
        run: npm run lint
