name: CI

on:
  push:
    branches: '*'

jobs:
  Lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run lint
      - run: npx tsc


  Publish:
    runs-on: ubuntu-latest
    needs: Lint
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      
      - run: npm ci
      - run: npm run build
      - run: rm -rf docs/
      - run: mv public/ docs/

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Publish changes
          commit_options: '--no-verify --signoff'
          file_pattern: docs/*
          commit_user_name: KibiRaptor
          commit_user_email: KibiRaptor@protonmail.com
